import { NutriEntity, TrustScoreResult } from '../types/nutri';
import { DataHubContextKit } from './context-kit';
import { callUniversalLlm, LlmMessage } from './llm';

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export type AgentMode = 'governance' | 'talk_to_data';

/**
 * Generates an analytical response to user questions about a dataset's Nutri Trust Score,
 * lineage impact, concrete remediation steps, or Talk-to-Data SQL generation.
 */
export async function chatWithAnalyticsAgent(
  entity: NutriEntity,
  scoreResult: TrustScoreResult,
  userMessage: string,
  history: ChatMessage[] = [],
  mode: AgentMode = 'governance'
): Promise<string> {
  const packet = DataHubContextKit.buildContextPacket(entity, scoreResult);
  const promptContext = DataHubContextKit.toPromptContext(packet);
  const sqlSchemaContext = DataHubContextKit.toSqlContext(packet);

  const isLowTrust = scoreResult.trustScore < 70 || packet.allergens.length > 0;

  // =========================================================================
  // 1. Fallback Generation (Offline / Rule-based)
  // =========================================================================
  let fallbackResponse = '';
  if (mode === 'talk_to_data') {
    const warningBlock = isLowTrust
      ? `> [!WARNING]\n> **🚨 Data Nutrition Safety Warning (Trust Score: ${scoreResult.trustScore}/100)**\n> This dataset has active quality warnings: ${packet.allergens.join(', ') || 'Low overall governance score'}. Results should be audited before use in financial or executive reporting.\n\n`
      : `> [!NOTE]\n> **✅ Healthy Data Nutrition (Trust Score: ${scoreResult.trustScore}/100)**\n> Verified schema and passing assertions.\n\n`;

    fallbackResponse = `${warningBlock}### 💬 DataHub Talk-to-Data SQL for \`${entity.name}\` (${entity.platform.toUpperCase()})

\`\`\`sql
-- Query generated by Nutri Talk-to-Data Engine
-- Target Platform: ${entity.platform}
SELECT
${entity.fields.slice(0, 5).map((f) => `  ${f.fieldPath}`).join(',\n')}
FROM ${entity.name}
WHERE 1=1
ORDER BY 1 DESC
LIMIT 100;
\`\`\`

**Schema Context Grounding:**
* **Total Columns Available:** ${entity.fields.length} (${packet.schema.documentedFieldsCount} documented)
* **Target Dialect:** ${entity.platform.toUpperCase()}`;
  } else {
    fallbackResponse = `### 📊 Nutri Governance Diagnosis for \`${entity.name}\` (${entity.platform})
* **Overall Trust Score:** ${scoreResult.trustScore}/100
* **Freshness:** ${scoreResult.subScores.freshness}% (${scoreResult.breakdown.freshnessDetails})
* **Completeness:** ${scoreResult.subScores.completeness}% (${scoreResult.breakdown.completenessDetails})
* **Lineage Depth:** ${scoreResult.subScores.lineage}% (${scoreResult.breakdown.lineageDetails})
* **Test Coverage:** ${scoreResult.subScores.testCoverage}% (${scoreResult.breakdown.testCoverageDetails})

**Identified Metadata Gaps:**
${packet.schema.undocumentedFields.length > 0 ? `- **${packet.schema.undocumentedFields.length} Undocumented Columns:** ${packet.schema.undocumentedFields.map((f) => `\`${f}\``).slice(0, 5).join(', ')}` : '- All columns have descriptions.'}
${!packet.governance.hasOwner ? '- **Missing Owner:** No CorpUser or CorpGroup is assigned.' : `- **Owner:** ${packet.governance.owners.join(', ')}`}
${packet.quality.totalAssertions === 0 ? '- **Zero Quality Tests:** No dbt tests or DataHub assertions configured.' : ''}

**Recommended Action:**
${packet.schema.undocumentedFields.length > 0 ? 'Document missing columns in dbt `schema.yml` to raise Completeness.' : 'Add assertions to increase quality coverage.'}`;
  }

  // =========================================================================
  // 2. Universal LLM Prompt Execution (GMI Cloud / OpenAI / Gemini)
  // =========================================================================
  let systemPrompt = '';

  if (mode === 'talk_to_data') {
    systemPrompt = `You are DataHub Talk-to-Data Analytics Agent, an expert in writing precise, safe SQL grounded in DataHub metadata.

${promptContext}

Available Schema for SQL generation:
${sqlSchemaContext}

Rules for SQL Generation:
1. TRUST SAFETY CHECK: If Trust Score < 70 or active allergens exist, ALWAYS begin response with a bold markdown warning calling out the specific risks (e.g. failing assertions, stale data, unowned table).
2. Generate valid ${entity.platform.toUpperCase()} SQL formatted inside markdown \`\`\`sql blocks.
3. Use ONLY column names that exist in the schema above. NEVER invent or hallucinate column names.
4. If the user asks for a calculation, use correct SQL aggregation syntax and comment your logic.`;
  } else {
    systemPrompt = `You are Nutri Analytics Agent, an elite DataHub metadata and data governance remediation expert.
You are helping an engineer or analyst inspect and improve the health of the following dataset:

${promptContext}

Nutri Trust Score Breakdown:
- Overall Score: ${scoreResult.trustScore}/100
- Freshness: ${scoreResult.subScores.freshness}% (${scoreResult.breakdown.freshnessDetails})
- Completeness: ${scoreResult.subScores.completeness}% (${scoreResult.breakdown.completenessDetails})
- Lineage: ${scoreResult.subScores.lineage}% (${scoreResult.breakdown.lineageDetails})
- Test Coverage: ${scoreResult.subScores.testCoverage}% (${scoreResult.breakdown.testCoverageDetails})

Your Mission:
1. Answer the user's question accurately using ONLY grounded facts from the context above.
2. If asked how to reach a higher score (e.g. 90+), provide specific, quantified actions (e.g. "Document \`secret_token\` for +15 points").
3. If asked for code or schema patches, generate clean, ready-to-copy dbt schema.yml, SQL comments, or DataHub mutation snippets.
4. Keep answers structured and formatted in clean GitHub markdown.`;
  }

  const messages: LlmMessage[] = [
    { role: 'system', content: systemPrompt },
    ...history.map((h) => ({ role: h.role, content: h.content })),
    { role: 'user', content: userMessage },
  ];

  const llmResponse = await callUniversalLlm({
    messages,
    temperature: mode === 'talk_to_data' ? 0.1 : 0.3,
    maxTokens: 900,
  });

  return llmResponse || fallbackResponse;
}
