import { NutriEntity } from '../types/nutri';

export interface CatalogDataset {
  urn: string;
  name: string;
  platform: string;
}

export const APPROVED_SHOWCASE_DATASETS: CatalogDataset[] = [
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)', name: 'orders', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.order_items,PROD)', name: 'order_items', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.customers,PROD)', name: 'customers', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.products,PROD)', name: 'products', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.inventories,PROD)', name: 'inventories', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.shipments,PROD)', name: 'shipments', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.product_categories,PROD)', name: 'product_categories', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.suppliers,PROD)', name: 'suppliers', platform: 'snowflake' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.stg_orders,PROD)', name: 'stg_orders', platform: 'dbt' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)', name: 'fct_orders', platform: 'dbt' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.dim_customers,PROD)', name: 'dim_customers', platform: 'dbt' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_daily_revenue,PROD)', name: 'fct_daily_revenue', platform: 'dbt' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.users,PROD)', name: 'users', platform: 'postgres' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.payments,PROD)', name: 'payments', platform: 'postgres' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.audit_logs,PROD)', name: 'audit_logs', platform: 'postgres' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:tableau,executive_dashboards.sales_performance,PROD)', name: 'Sales Performance Dashboard', platform: 'tableau' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:powerbi,finance_reports.quarterly_burn,PROD)', name: 'Quarterly Financial Burn', platform: 'powerbi' },
  { urn: 'urn:li:dataset:(urn:li:dataPlatform:looker,marketing_analytics.campaign_roi,PROD)', name: 'Campaign ROI Explorer', platform: 'looker' },
];

const now = Date.now();
const HOUR = 3600 * 1000;

export const SHOWCASE_ENTITIES_MAP: Record<string, NutriEntity> = {
  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)',
    name: 'orders',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Raw transactions ingested hourly from transactional PostgreSQL read-replicas into Snowflake staging schema.',
    owners: ['urn:li:corpuser:sarah.chen@company.com', 'urn:li:corpGroup:data-engineering'],
    domain: 'Sales & Revenue',
    glossaryTerms: ['Core Entity', 'Financial Record'],
    tags: ['Tier 1 - High Priority', 'Authoritative Source'],
    lastModifiedTimestamp: now - (2.5 * HOUR),
    fields: [
      { fieldPath: 'order_id', type: 'VARCHAR(64)', description: 'Primary key UUID for customer purchase orders', tags: ['Identifier'], glossaryTerms: ['Primary Key'] },
      { fieldPath: 'customer_id', type: 'VARCHAR(64)', description: 'Foreign key reference to customer record', tags: ['Identifier', 'PII_Data'], glossaryTerms: [] },
      { fieldPath: 'order_status', type: 'VARCHAR(32)', description: 'Current state: PENDING, PROCESSED, SHIPPED, or CANCELLED', tags: [], glossaryTerms: ['Order State'] },
      { fieldPath: 'order_total_usd', type: 'DECIMAL(12,2)', description: 'Gross order amount before discounts and taxes', tags: ['Monetary Value'], glossaryTerms: ['Revenue'] },
      { fieldPath: 'tax_amount', type: 'DECIMAL(8,2)', description: 'State and federal taxes levied', tags: ['Financial'], glossaryTerms: [] },
      { fieldPath: 'shipping_method', type: 'VARCHAR(32)', description: 'Standard, Expedited, or Same-Day Carrier', tags: [], glossaryTerms: [] },
      { fieldPath: 'created_at', type: 'TIMESTAMP_NTZ', description: 'UTC timestamp when transaction was committed', tags: ['Timestamp'], glossaryTerms: [] },
      { fieldPath: 'updated_at', type: 'TIMESTAMP_NTZ', description: 'Last state change timestamp', tags: ['Timestamp'], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.payments,PROD)'],
    downstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.stg_orders,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)',
    ],
    upstreamPlatforms: ['postgres'],
    assertions: [
      { urn: 'urn:li:assertion:order_id_unique', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
      { urn: 'urn:li:assertion:order_total_positive', type: 'VOLUME', passed: true, lastRunTimestamp: now - HOUR },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.order_items,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.order_items,PROD)',
    name: 'order_items',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Line item breakdown for each customer transaction including SKU, quantity, and applied promotion codes.',
    owners: ['urn:li:corpuser:sarah.chen@company.com'],
    domain: 'Sales & Revenue',
    glossaryTerms: ['Line Items'],
    tags: ['Authoritative Source'],
    lastModifiedTimestamp: now - (3.1 * HOUR),
    fields: [
      { fieldPath: 'item_id', type: 'VARCHAR(64)', description: 'Unique identifier for item record', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'order_id', type: 'VARCHAR(64)', description: 'Parent order identifier reference', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'product_id', type: 'VARCHAR(64)', description: 'Product catalog SKU', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'quantity', type: 'INTEGER', description: 'Quantity purchased', tags: [], glossaryTerms: [] },
      { fieldPath: 'unit_price', type: 'DECIMAL(10,2)', description: 'Item unit price at time of order', tags: ['Financial'], glossaryTerms: [] },
      { fieldPath: 'discount_amount', type: 'DECIMAL(8,2)', description: 'Discount applied to line item', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: [],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)'],
    upstreamPlatforms: [],
    assertions: [
      { urn: 'urn:li:assertion:item_quantity_positive', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (2 * HOUR) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.customers,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.customers,PROD)',
    name: 'customers',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Master customer accounts table containing contact info, billing addresses, and privacy consents.',
    owners: ['urn:li:corpuser:alex.miller@company.com', 'urn:li:corpGroup:privacy-security'],
    domain: 'Customer 360',
    glossaryTerms: ['Customer Record', 'Master Data'],
    tags: ['PII_Data', 'Tier 1 - High Priority', 'GDPR Restricted'],
    lastModifiedTimestamp: now - (5 * HOUR),
    fields: [
      { fieldPath: 'customer_id', type: 'VARCHAR(64)', description: 'Master customer UUID', tags: ['Identifier'], glossaryTerms: ['Primary Key'] },
      { fieldPath: 'email', type: 'VARCHAR(255)', description: 'Hashed customer email address', tags: ['PII_Data', 'Email'], glossaryTerms: [] },
      { fieldPath: 'first_name', type: 'VARCHAR(128)', description: 'Customer legal first name', tags: ['PII_Data'], glossaryTerms: [] },
      { fieldPath: 'last_name', type: 'VARCHAR(128)', description: 'Customer legal last name', tags: ['PII_Data'], glossaryTerms: [] },
      { fieldPath: 'phone_number', type: 'VARCHAR(32)', description: 'SMS verified contact phone number', tags: ['PII_Data', 'Phone'], glossaryTerms: [] },
      { fieldPath: 'billing_country', type: 'VARCHAR(2)', description: 'ISO-3166 alpha-2 country code', tags: ['Geographic'], glossaryTerms: [] },
      { fieldPath: 'signup_source', type: 'VARCHAR(64)', description: 'Acquisition channel (Organic, Paid, Affiliate)', tags: [], glossaryTerms: [] },
      { fieldPath: 'gdpr_consent_status', type: 'BOOLEAN', description: 'Explicit opt-in status for tracking and analytics', tags: ['Compliance'], glossaryTerms: ['GDPR'] },
      { fieldPath: 'created_at', type: 'TIMESTAMP_NTZ', description: 'Account creation date', tags: ['Timestamp'], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.users,PROD)'],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.dim_customers,PROD)'],
    upstreamPlatforms: ['postgres'],
    assertions: [
      { urn: 'urn:li:assertion:email_format_valid', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
      { urn: 'urn:li:assertion:no_duplicate_customers', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
      { urn: 'urn:li:assertion:gdpr_audit_compliant', type: 'SQL_CUSTOM', passed: true, lastRunTimestamp: now - HOUR },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.products,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.products,PROD)',
    name: 'products',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Master SKU product catalog including retail pricing, inventory categories, and brand metadata.',
    owners: ['urn:li:corpuser:marcus.vance@company.com'],
    domain: 'Merchandising',
    glossaryTerms: ['Product Master'],
    tags: ['Authoritative Source'],
    lastModifiedTimestamp: now - (6 * HOUR),
    fields: [
      { fieldPath: 'product_id', type: 'VARCHAR(64)', description: 'Master product SKU', tags: ['Identifier'], glossaryTerms: ['Primary Key'] },
      { fieldPath: 'product_name', type: 'VARCHAR(255)', description: 'Commercial product listing title', tags: [], glossaryTerms: [] },
      { fieldPath: 'category_id', type: 'VARCHAR(64)', description: 'Foreign key to product_categories', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'retail_price_usd', type: 'DECIMAL(10,2)', description: 'MSRP manufacturer list price', tags: ['Financial'], glossaryTerms: [] },
      { fieldPath: 'is_active', type: 'BOOLEAN', description: 'Available for consumer checkout', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.product_categories,PROD)'],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.order_items,PROD)'],
    upstreamPlatforms: ['snowflake'],
    assertions: [
      { urn: 'urn:li:assertion:product_price_positive', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (4 * HOUR) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.inventories,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.inventories,PROD)',
    name: 'inventories',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Real-time fulfillment warehouse stock quantities and reserve thresholds.',
    owners: ['urn:li:corpuser:marcus.vance@company.com'],
    domain: 'Supply Chain',
    glossaryTerms: ['Warehouse Stock'],
    tags: ['Operational'],
    lastModifiedTimestamp: now - (1.1 * HOUR),
    fields: [
      { fieldPath: 'warehouse_id', type: 'VARCHAR(32)', description: 'Fulfillment distribution center code', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'product_id', type: 'VARCHAR(64)', description: 'Stock SKU identifier', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'quantity_on_hand', type: 'INTEGER', description: 'Physical units located in facility bins', tags: [], glossaryTerms: [] },
      { fieldPath: 'reorder_point', type: 'INTEGER', description: 'Minimum reserve stock triggering supplier purchase order', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.products,PROD)'],
    downstreamUrns: [],
    upstreamPlatforms: ['snowflake'],
    assertions: [
      { urn: 'urn:li:assertion:inventory_non_negative', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.shipments,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.shipments,PROD)',
    name: 'shipments',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Logistics delivery tracking status and carrier tracking numbers.',
    owners: ['urn:li:corpuser:logistics-lead@company.com'],
    domain: 'Supply Chain',
    glossaryTerms: ['Logistics Tracking'],
    tags: ['Tier 2'],
    lastModifiedTimestamp: now - (3.5 * HOUR),
    fields: [
      { fieldPath: 'shipment_id', type: 'VARCHAR(64)', description: 'Logistics manifest UUID', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'order_id', type: 'VARCHAR(64)', description: 'Fulfillable order reference', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'carrier', type: 'VARCHAR(32)', description: 'FedEx, UPS, DHL, or USPS', tags: [], glossaryTerms: [] },
      { fieldPath: 'tracking_number', type: 'VARCHAR(128)', description: 'Carrier tracking identifier', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'delivered_at', type: 'TIMESTAMP_NTZ', description: 'Delivery confirmation timestamp', tags: ['Timestamp'], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)'],
    downstreamUrns: [],
    upstreamPlatforms: ['snowflake'],
    assertions: [],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.product_categories,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.product_categories,PROD)',
    name: 'product_categories',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Taxonomy hierarchy of merchandise departments and sub-categories.',
    owners: ['urn:li:corpuser:marcus.vance@company.com'],
    domain: 'Merchandising',
    glossaryTerms: ['Product Taxonomy'],
    tags: ['Reference Data'],
    lastModifiedTimestamp: now - (24 * HOUR),
    fields: [
      { fieldPath: 'category_id', type: 'VARCHAR(64)', description: 'Category unique identifier', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'category_name', type: 'VARCHAR(128)', description: 'Display name for category', tags: [], glossaryTerms: [] },
      { fieldPath: 'department', type: 'VARCHAR(64)', description: 'Apparel, Electronics, Home, or Beauty', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: [],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.products,PROD)'],
    upstreamPlatforms: [],
    assertions: [
      { urn: 'urn:li:assertion:category_unique', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (12 * HOUR) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.suppliers,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.suppliers,PROD)',
    name: 'suppliers',
    platform: 'snowflake',
    entityType: 'DATASET',
    description: 'Direct manufacturer partner vendor profiles, contact emails, and payment terms.',
    owners: ['urn:li:corpuser:procurement@company.com'],
    domain: 'Procurement',
    glossaryTerms: ['Vendor Master'],
    tags: ['Confidential', 'Vendor Information'],
    lastModifiedTimestamp: now - (48 * HOUR),
    fields: [
      { fieldPath: 'supplier_id', type: 'VARCHAR(64)', description: 'Vendor master ID', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'company_name', type: 'VARCHAR(255)', description: 'Corporate entity legal name', tags: [], glossaryTerms: [] },
      { fieldPath: 'contact_email', type: 'VARCHAR(255)', description: 'Representative email', tags: ['PII_Data', 'Email'], glossaryTerms: [] },
      { fieldPath: 'country_code', type: 'VARCHAR(2)', description: 'Country of origin', tags: ['Geographic'], glossaryTerms: [] },
    ],
    upstreamUrns: [],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.products,PROD)'],
    upstreamPlatforms: [],
    assertions: [],
  },

  'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)',
    name: 'fct_orders',
    platform: 'dbt',
    entityType: 'DATASET',
    description: 'Gold-standard star-schema facts table unifying raw orders, line items, promotion attribution, and tax calculations.',
    owners: ['urn:li:corpuser:david.kim@company.com', 'urn:li:corpGroup:analytics-engineers'],
    domain: 'Sales & Revenue',
    glossaryTerms: ['Fact Table', 'Executive Metric'],
    tags: ['Gold Standard', 'Production Ready', 'Authoritative Source', 'SLA: 99.9%'],
    lastModifiedTimestamp: now - (45 * 60 * 1000), // 45m ago
    fields: [
      { fieldPath: 'order_key', type: 'VARCHAR(64)', description: 'Surrogate hash key for transaction fact row', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'customer_key', type: 'VARCHAR(64)', description: 'Foreign key to dim_customers dimension', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'order_date_key', type: 'INTEGER', description: 'Date dimension join key (YYYYMMDD)', tags: ['Date Key'], glossaryTerms: [] },
      { fieldPath: 'gross_revenue_usd', type: 'DECIMAL(14,2)', description: 'Total item sales amount before returns and refunds', tags: ['Financial'], glossaryTerms: ['Revenue'] },
      { fieldPath: 'net_revenue_usd', type: 'DECIMAL(14,2)', description: 'Recognized accounting revenue after promotional coupon deductions', tags: ['Financial', 'Metric'], glossaryTerms: ['Net Revenue'] },
      { fieldPath: 'item_count', type: 'INTEGER', description: 'Total count of individual units in purchase order', tags: ['Volume'], glossaryTerms: [] },
      { fieldPath: 'fulfillment_duration_hours', type: 'FLOAT', description: 'Elapsed hours between payment confirmation and carrier scan', tags: ['Performance'], glossaryTerms: [] },
    ],
    upstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.order_items,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.stg_orders,PROD)',
    ],
    downstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:tableau,executive_dashboards.sales_performance,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:powerbi,finance_reports.quarterly_burn,PROD)',
    ],
    upstreamPlatforms: ['snowflake', 'dbt'],
    assertions: [
      { urn: 'urn:li:assertion:fct_orders_pk_unique', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (30 * 60 * 1000) },
      { urn: 'urn:li:assertion:fct_orders_revenue_not_null', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (30 * 60 * 1000) },
      { urn: 'urn:li:assertion:fct_orders_date_sane', type: 'VOLUME', passed: true, lastRunTimestamp: now - (30 * 60 * 1000) },
      { urn: 'urn:li:assertion:fct_orders_reconciliation_zero_diff', type: 'SQL_CUSTOM', passed: true, lastRunTimestamp: now - (30 * 60 * 1000) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.dim_customers,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.dim_customers,PROD)',
    name: 'dim_customers',
    platform: 'dbt',
    entityType: 'DATASET',
    description: 'Type 2 Slowly Changing Dimension tracking customer lifetime value, RFM segmentations, and tier cohorts.',
    owners: ['urn:li:corpuser:david.kim@company.com', 'urn:li:corpGroup:marketing-ops'],
    domain: 'Customer 360',
    glossaryTerms: ['Dimension Table', 'Customer Segmentation'],
    tags: ['PII_Data', 'Gold Standard', 'Production Ready'],
    lastModifiedTimestamp: now - (1.2 * HOUR),
    fields: [
      { fieldPath: 'customer_key', type: 'VARCHAR(64)', description: 'Surrogate dimension key', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'customer_id', type: 'VARCHAR(64)', description: 'Natural customer identifier', tags: ['Identifier', 'PII_Data'], glossaryTerms: [] },
      { fieldPath: 'lifetime_value_usd', type: 'DECIMAL(12,2)', description: 'Cumulative historic purchase volume', tags: ['Metric'], glossaryTerms: ['LTV'] },
      { fieldPath: 'rfm_segment', type: 'VARCHAR(32)', description: 'Customer cohort: Champions, Loyal, At-Risk, or Churned', tags: ['Classification'], glossaryTerms: [] },
      { fieldPath: 'is_active', type: 'BOOLEAN', description: 'Active status in current dimension snapshot', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.customers,PROD)'],
    downstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:tableau,executive_dashboards.sales_performance,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:looker,marketing_analytics.campaign_roi,PROD)',
    ],
    upstreamPlatforms: ['snowflake'],
    assertions: [
      { urn: 'urn:li:assertion:dim_cust_unique_pk', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
      { urn: 'urn:li:assertion:ltv_non_negative', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.stg_orders,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.stg_orders,PROD)',
    name: 'stg_orders',
    platform: 'dbt',
    entityType: 'DATASET',
    description: 'Cleaned and type-cast staging view sitting directly on raw Snowflake orders table.',
    owners: ['urn:li:corpuser:david.kim@company.com'],
    domain: 'Sales & Revenue',
    glossaryTerms: ['Staging Model'],
    tags: ['Silver Standard'],
    lastModifiedTimestamp: now - (2 * HOUR),
    fields: [
      { fieldPath: 'order_id', type: 'VARCHAR(64)', description: 'Cleaned UUID', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'order_status_clean', type: 'VARCHAR(32)', description: 'Normalized uppercase status code', tags: [], glossaryTerms: [] },
      { fieldPath: 'order_amount', type: 'DECIMAL(12,2)', description: 'Validated amount in USD', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)'],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)'],
    upstreamPlatforms: ['snowflake'],
    assertions: [
      { urn: 'urn:li:assertion:stg_orders_unique', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (2 * HOUR) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_daily_revenue,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_daily_revenue,PROD)',
    name: 'fct_daily_revenue',
    platform: 'dbt',
    entityType: 'DATASET',
    description: 'Aggregated financial rollup of daily GAAP revenue, refunds, and promo subsidies.',
    owners: ['urn:li:corpuser:elena.rostova@company.com', 'urn:li:corpGroup:finance-analytics'],
    domain: 'Finance',
    glossaryTerms: ['Financial Summary', 'Daily Metrics'],
    tags: ['Tier 1 - High Priority', 'SOX Sensitive'],
    lastModifiedTimestamp: now - (1.5 * HOUR),
    fields: [
      { fieldPath: 'revenue_date', type: 'DATE', description: 'Calendar accounting date', tags: ['Date'], glossaryTerms: [] },
      { fieldPath: 'total_orders_count', type: 'INTEGER', description: 'Count of completed sales', tags: [], glossaryTerms: [] },
      { fieldPath: 'daily_gross_usd', type: 'DECIMAL(16,2)', description: 'Gross revenue recognized', tags: ['Financial'], glossaryTerms: [] },
      { fieldPath: 'daily_net_usd', type: 'DECIMAL(16,2)', description: 'Net GAAP revenue after returns', tags: ['Financial', 'Metric'], glossaryTerms: [] },
    ],
    upstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)'],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:powerbi,finance_reports.quarterly_burn,PROD)'],
    upstreamPlatforms: ['dbt'],
    assertions: [
      { urn: 'urn:li:assertion:revenue_date_continuous', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - HOUR },
      { urn: 'urn:li:assertion:daily_net_less_than_gross', type: 'SQL_CUSTOM', passed: true, lastRunTimestamp: now - HOUR },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.users,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.users,PROD)',
    name: 'users',
    platform: 'postgres',
    entityType: 'DATASET',
    description: 'Application database live authentication and profiles table.',
    owners: ['urn:li:corpuser:jordan.lee@company.com'],
    domain: 'Core App',
    glossaryTerms: ['User Profiles'],
    tags: ['PII_Data', 'Live OLTP'],
    lastModifiedTimestamp: now - (8 * HOUR),
    fields: [
      { fieldPath: 'id', type: 'BIGINT', description: 'Auto-incrementing user ID', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'email', type: 'TEXT', description: 'User login email address', tags: ['PII_Data', 'Email'], glossaryTerms: [] },
      { fieldPath: 'password_hash', type: 'TEXT', description: 'Bcrypt salted credential hash', tags: ['Sensitive Security'], glossaryTerms: [] },
      { fieldPath: 'is_verified', type: 'BOOLEAN', description: 'Two-factor auth status', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: [],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.customers,PROD)'],
    upstreamPlatforms: [],
    assertions: [],
  },

  'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.payments,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.payments,PROD)',
    name: 'payments',
    platform: 'postgres',
    entityType: 'DATASET',
    description: 'Live transactional gateway payment ledger. Warning: 1 assertion failing due to ledger drift.',
    owners: ['urn:li:corpuser:elena.rostova@company.com'],
    domain: 'Finance',
    glossaryTerms: ['Payment Records'],
    tags: ['PCI DSS', 'Financial', 'Needs Attention'],
    lastModifiedTimestamp: now - (14 * HOUR),
    fields: [
      { fieldPath: 'payment_id', type: 'VARCHAR(64)', description: 'Stripe charge reference ID', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'order_id', type: 'VARCHAR(64)', description: 'Internal transaction reference', tags: ['Identifier'], glossaryTerms: [] },
      { fieldPath: 'amount_cents', type: 'INTEGER', description: 'Charge amount in integer cents', tags: ['Financial'], glossaryTerms: [] },
      { fieldPath: 'currency', type: 'VARCHAR(3)', description: 'ISO currency symbol', tags: [], glossaryTerms: [] },
      { fieldPath: 'charge_status', type: 'VARCHAR(32)', description: 'captured, failed, or refunded', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: [],
    downstreamUrns: ['urn:li:dataset:(urn:li:dataPlatform:snowflake,ecommerce_db.public.orders,PROD)'],
    upstreamPlatforms: [],
    assertions: [
      { urn: 'urn:li:assertion:payment_amount_valid', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (10 * HOUR) },
      { urn: 'urn:li:assertion:stripe_ledger_reconciliation', type: 'SQL_CUSTOM', passed: false, lastRunTimestamp: now - (2 * HOUR) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.audit_logs,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,app_db.public.audit_logs,PROD)',
    name: 'audit_logs',
    platform: 'postgres',
    entityType: 'DATASET',
    description: 'Legacy application audit logging table. Missing defined technical owner and stale ingestion pipeline.',
    owners: [],
    domain: undefined,
    glossaryTerms: [],
    tags: ['Unowned Asset', 'Deprecation Candidate'],
    lastModifiedTimestamp: now - (180 * HOUR), // Stale (> 7 days)
    fields: [
      { fieldPath: 'log_id', type: 'BIGINT', description: '', tags: [], glossaryTerms: [] },
      { fieldPath: 'event_name', type: 'TEXT', description: '', tags: [], glossaryTerms: [] },
      { fieldPath: 'payload_json', type: 'JSONB', description: '', tags: [], glossaryTerms: [] },
    ],
    upstreamUrns: [],
    downstreamUrns: [],
    upstreamPlatforms: [],
    assertions: [],
  },

  'urn:li:dataset:(urn:li:dataPlatform:tableau,executive_dashboards.sales_performance,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:tableau,executive_dashboards.sales_performance,PROD)',
    name: 'Sales Performance Dashboard',
    platform: 'tableau',
    entityType: 'DASHBOARD',
    description: 'C-Suite executive dashboard tracking quarterly ARR targets, sales representative quotas, and region growth.',
    owners: ['urn:li:corpuser:rachel.zane@company.com', 'urn:li:corpGroup:executive-leadership'],
    domain: 'Executive Reporting',
    glossaryTerms: ['Executive Dashboard', 'ARR Metrics'],
    tags: ['Tier 1 - High Priority', 'Board Deck Certified'],
    lastModifiedTimestamp: now - (1.8 * HOUR),
    fields: [
      { fieldPath: 'region_code', type: 'STRING', description: 'Global sales theater (AMER, EMEA, APAC)', tags: [], glossaryTerms: [] },
      { fieldPath: 'quota_attainment_pct', type: 'FLOAT', description: 'Percentage quota achieved against board targets', tags: ['KPI'], glossaryTerms: [] },
      { fieldPath: 'closed_won_arr_usd', type: 'DECIMAL(16,2)', description: 'Annual Recurring Revenue committed', tags: ['Financial'], glossaryTerms: [] },
    ],
    upstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.dim_customers,PROD)',
    ],
    downstreamUrns: [],
    upstreamPlatforms: ['dbt'],
    assertions: [
      { urn: 'urn:li:assertion:tableau_extract_freshness', type: 'FRESHNESS', passed: true, lastRunTimestamp: now - HOUR },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:powerbi,finance_reports.quarterly_burn,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:powerbi,finance_reports.quarterly_burn,PROD)',
    name: 'Quarterly Financial Burn',
    platform: 'powerbi',
    entityType: 'DASHBOARD',
    description: 'Corporate finance cash runway, operating expense burn rate, and capital expenditure monitoring.',
    owners: ['urn:li:corpuser:elena.rostova@company.com'],
    domain: 'Finance',
    glossaryTerms: ['Runway Metrics'],
    tags: ['SOX Sensitive', 'Restricted Access'],
    lastModifiedTimestamp: now - (18 * HOUR),
    fields: [
      { fieldPath: 'fiscal_quarter', type: 'STRING', description: 'Current fiscal quarter (e.g. Q3-2026)', tags: [], glossaryTerms: [] },
      { fieldPath: 'cash_balance_usd', type: 'DECIMAL(16,2)', description: 'Liquid cash assets in treasury', tags: ['Treasury'], glossaryTerms: [] },
      { fieldPath: 'monthly_burn_rate_usd', type: 'DECIMAL(14,2)', description: 'Net cash outflow per 30 day period', tags: ['Expense'], glossaryTerms: [] },
    ],
    upstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_daily_revenue,PROD)',
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.fct_orders,PROD)',
    ],
    downstreamUrns: [],
    upstreamPlatforms: ['dbt'],
    assertions: [
      { urn: 'urn:li:assertion:powerbi_sox_reconciliation', type: 'SQL_CUSTOM', passed: true, lastRunTimestamp: now - (6 * HOUR) },
    ],
  },

  'urn:li:dataset:(urn:li:dataPlatform:looker,marketing_analytics.campaign_roi,PROD)': {
    urn: 'urn:li:dataset:(urn:li:dataPlatform:looker,marketing_analytics.campaign_roi,PROD)',
    name: 'Campaign ROI Explorer',
    platform: 'looker',
    entityType: 'DASHBOARD',
    description: 'Self-serve marketing attribution explore model measuring customer acquisition cost across paid channels.',
    owners: ['urn:li:corpuser:jordan.lee@company.com'],
    domain: 'Growth Marketing',
    glossaryTerms: ['Marketing Attribution'],
    tags: ['Self-Serve Analytics'],
    lastModifiedTimestamp: now - (28 * HOUR),
    fields: [
      { fieldPath: 'ad_network', type: 'STRING', description: 'Google Ads, Meta, LinkedIn, TikTok', tags: [], glossaryTerms: [] },
      { fieldPath: 'blended_cac_usd', type: 'DECIMAL(10,2)', description: 'Customer acquisition cost per signed contract', tags: ['CAC'], glossaryTerms: [] },
      { fieldPath: 'return_on_ad_spend_mult', type: 'FLOAT', description: 'ROAS revenue multiplier (e.g. 4.2x)', tags: ['Performance'], glossaryTerms: [] },
    ],
    upstreamUrns: [
      'urn:li:dataset:(urn:li:dataPlatform:dbt,ecommerce_analytics.dim_customers,PROD)',
    ],
    downstreamUrns: [],
    upstreamPlatforms: ['dbt'],
    assertions: [
      { urn: 'urn:li:assertion:looker_view_compiled', type: 'DATA_QUALITY', passed: true, lastRunTimestamp: now - (12 * HOUR) },
    ],
  },
};
